classDiagram
    class User {
    - UUID4 id
    - string first name
    - string last name
    - string email
    - string password
    + bool verificationConnexion()
}
    class Review {
    - UUID4 id
    - string comment
    - string place
    - string user
    + rating
    + get_review()
    + creat_message()
    + update_message()
}

User -- Review : composition

class Place {
    - UUID4 id
    - string title
    - string description
    - sting price
    - string latitude
    - string longitude
    + get_review()
    + get_picture()

}

class Amenity {
    - UUID4 id
    + string name
    + string description

}

Place -- Amenity : Composotion